// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgGaH0DicNCHwQCvGPuCRr9Zpl0_puXA',
    appId: '1:404628906818:web:ae03d238e864fa66701edb',
    messagingSenderId: '404628906818',
    projectId: 'kyoto-travel-app-d3f08',
    authDomain: 'kyoto-travel-app-d3f08.firebaseapp.com',
    storageBucket: 'kyoto-travel-app-d3f08.firebasestorage.app',
    measurementId: 'G-EFB5VPMSFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeMRPuRQ1Ju2Z6WPTQXxRu6iBKfunMxQ',
    appId: '1:404628906818:android:79d197b2c9103837701edb',
    messagingSenderId: '404628906818',
    projectId: 'kyoto-travel-app-d3f08',
    storageBucket: 'kyoto-travel-app-d3f08.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5WThasSlsoxx_uWrgIDHxMRFXqiIm9rA',
    appId: '1:404628906818:ios:f482e7372ffed0b2701edb',
    messagingSenderId: '404628906818',
    projectId: 'kyoto-travel-app-d3f08',
    storageBucket: 'kyoto-travel-app-d3f08.firebasestorage.app',
    androidClientId: '404628906818-kh2fbphplbvcj39iupfu1a21gbim0vuo.apps.googleusercontent.com',
    iosClientId: '404628906818-ccvqmd5g1c4slrtioohutp7cu88nnpdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyotoTravelApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5WThasSlsoxx_uWrgIDHxMRFXqiIm9rA',
    appId: '1:404628906818:ios:f482e7372ffed0b2701edb',
    messagingSenderId: '404628906818',
    projectId: 'kyoto-travel-app-d3f08',
    storageBucket: 'kyoto-travel-app-d3f08.firebasestorage.app',
    androidClientId: '404628906818-kh2fbphplbvcj39iupfu1a21gbim0vuo.apps.googleusercontent.com',
    iosClientId: '404628906818-ccvqmd5g1c4slrtioohutp7cu88nnpdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyotoTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgGaH0DicNCHwQCvGPuCRr9Zpl0_puXA',
    appId: '1:404628906818:web:1b583d90788779f1701edb',
    messagingSenderId: '404628906818',
    projectId: 'kyoto-travel-app-d3f08',
    authDomain: 'kyoto-travel-app-d3f08.firebaseapp.com',
    storageBucket: 'kyoto-travel-app-d3f08.firebasestorage.app',
    measurementId: 'G-W727QGWX7L',
  );
}
